name: C/C++ CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-22.04-arm

    steps:
    - uses: actions/checkout@v4
    - name: make
      run: make
    # 将编译产物安装到临时目录，方便收集
    - name: Install to staging directory
      run: make install DESTDIR=${{ github.workspace }}/install

    # 上传整个安装目录作为产物（可根据需要精确指定文件）
    - name: Upload ARM64 artifact
      uses: actions/upload-artifact@v4
      with:
        name: arm64-binaries
        path: ${{ github.workspace }}/install/
        retention-days: 7   # 保留天数，可按需调整
